apps/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
# from api.views import index
from api.views import index, orders

app_name = "api"
urlpatterns = [
    url(r'^$', index.index, name="index"),
    url(r'^order/create/$', orders.create_order, name="create_order"),
]

apps/chief/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from . import views

app_name = "chief"
urlpatterns = [
    url(r'^$', views.ProjectList.as_view(), name='index'),


    url(r'^projects/$', views.ProjectList.as_view(), name='projects'),
    url(r'^project/(?P<pk>[0-9]+)/$', views.ProjectDetails.as_view(), name='project'),
    url(r'^project/create/$', views.ProjectCreate.as_view(), name='project_create'),
    url(r'^project/upd/(?P<pk>[0-9]+)/$', views.ProjectUpdate.as_view(), name='project_upd'),
    url(r'^project/del/(?P<pk>[0-9]+)/$', views.ProjectDelete.as_view(), name='project_del'),


    url(r'^project/(?P<project_pk>[0-9]+)/orders/upd/(?P<order_pk>[0-9]+)/$', views.OrderUpdate.as_view(), name='order_upd'),
    url(r'^orders/del/(?P<pk>[0-9]+)/$', views.OrderDelete.as_view(), name='order_del'),
    url(r'^project/(?P<project_pk>[0-9]+)/orders/create/$', views.OrderCreate.as_view(), name='order_create'),


    url(r'^project/(?P<project_pk>[0-9]+)/orders/fields/$', views.OrderFieldList.as_view(), name='ord_field_list'),
    url(r'^project/(?P<project_pk>[0-9]+)/orders/fields/create/$', views.OrderFieldCreate.as_view(), name='ord_field_create'),
    url(r'^orders/fields/upd/(?P<pk>[0-9]+)/$', views.OrderFieldUpdate.as_view(), name='ord_field_upd'),
    url(r'^orders/fields/del/(?P<pk>[0-9]+)/$', views.OrderFieldDelete.as_view(), name='ord_field_del'),


    url(r'^project/(?P<project_pk>[0-9]+)/invites/$', views.InviteList.as_view(), name='invites'),
    url(r'^invites/del/(?P<pk>[0-9]+)/$', views.InviteDelete.as_view(), name='invite_del'),
    url(r'^invites/create/$', views.InviteCreate.as_view(), name='invite_create'),


    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
]

apps/front/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', views.msg_logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^home/$', views.home, name='home')
]

apps/metaord/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from metaord import settings
from metaord.models import MetaordSettings
from metaord.views import SettingsUpdate


# if settings.DEBUG:
handler404 = 'metaord.views.page_not_found'
handler500 = 'metaord.views.error_view'
handler400 = 'metaord.views.error_view'


urlpatterns = [
    url(r'^', include('front.urls')),
    url(r'^settings/$', SettingsUpdate.as_view(), name='metaord_settings'),
    url(r'^chief/', include('chief.urls')),
    url(r'^webms/', include('webms.urls')),
    url(r'^worker/', include('worker.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/webms/urls.py
from django.conf.urls import include, url
from webms import views

app_name = "webms"
urlpatterns = [
    url(r'^$', views.InviteList.as_view(), name="index"),
    url(r'^$', views.InviteList.as_view(), name="invites"),

    url(r'^invites/(?P<pk>[0-9]+)/upd_status/$', views.InviteUpdateStatus.as_view(), name="invite_upd_status"),

    url(r'^register/$', views.RegistrationView.as_view(), name="register"),
]

apps/worker/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views # del
from django.conf.urls import include
from . import views
from metaord import views as meta_views

app_name = "worker"
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),

    url(r'^register/$', views.register_operator_form, name='register'),
    url(r'^register_submit/$', views.register_operator_submit, name='register_submit'),

    url(r'^orders/$', views.OrderList.as_view(), name='orders'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.OrderDetail.as_view(), name='order'),
    url(r'^orders/upd_status/(?P<pk>[0-9]+)/$', views.OrderUpdate.as_view(), name='order_upd_status'),
]

apps/front/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User, Permission
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.http import require_GET, require_POST
from django.shortcuts import redirect
from metaord.utils.auth import Groups
import logging


# logger = logging.getLogger(__name__) # todo

def index(request):
    return render(request, 'front/index.html', {})

def msg_logout(request, *args, **kwargs):
    messages.success(request, 'Вы вышли из профиля')
    return auth_views.logout(request, *args, **kwargs)

def home(request, *args, **kwargs):
    assert request.user.is_authenticated()
    url = '/chief' if Groups.is_user_chief(request.user) else '/worker'
    return redirect(url, args, kwargs)

apps/front/templates/front/index.html
{% extends 'metaord/layouts/basic.html' %}

{% block content %}
  <div class="row"><!-- / Sub menu ads -->
    <div class="col-md-6">
      <div class="row mb4">
        <div class="col-md-6">
          <div class="btn-group btn-block">
            <button data-toggle="dropdown" class="btn btn-success btn-lg dropdown-toggle col-lg-12">
              Вход <span class="caret"></span>
            </button>
            <ul class="dropdown-menu col-lg-12">
              <li>
                <a href="{% url 'login' %}?next=/chief/">Предпринимателям</a>
              </li>
              <li>
                <a href="{% url 'login' %}?next=/worker/">Операторам</a>
              </li>
              <li>
                <a href="{% url 'login' %}?next=/webms/">Web-мастерам</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-6">
          <div class="btn-group btn-block">
            <button data-toggle="dropdown" class="btn btn-success btn-lg dropdown-toggle col-lg-12">
              Регистрация <span class="caret"></span>
            </button>
            <ul class="dropdown-menu col-lg-12">
              <li>
                <a href="{% url 'chief:register' %}">Предпринимателям</a>
              </li>
              <li>
                <a href="{% url 'worker:register' %}">Операторам</a>
              </li>
              <li>
                <a href="{% url 'webms:register' %}">Операторам</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row mb2">
        <div class="col-md-12 txt-center">
          <img alt="Bootstrap Image Preview" src="http://lorempixel.com/g/400/200/" />
        </div>
      </div>
      <div class="row mb2">
        <div class="col-md-12 txt-center">
          <p class="lead">Зазывающий текст</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="jumbotron well">
        <h2>Почему Metaorder CRM?</h2>
        {% lorem 1 p %}
        <p>
          <a class="btn btn-primary btn-large" href="#"><span>Learn more</span></a>
        </p>
      </div>
    </div>
  </div> <!-- / Sub menu ads -->

  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img alt="Bootstrap Thumbnail First" src="http://lorempixel.com/output/people-q-c-600-200-1.jpg"/>
            <div class="caption">
              <h3>
                Thumbnail label
              </h3>
              <p>
                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
              <p>
                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img alt="Bootstrap Thumbnail Second" src="http://lorempixel.com/output/city-q-c-600-200-1.jpg"/>
            <div class="caption">
              <h3>
                Thumbnail label
              </h3>
              <p>
                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
              <p>
                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img alt="Bootstrap Thumbnail Third" src="http://lorempixel.com/output/sports-q-c-600-200-1.jpg"/>
            <div class="caption">
              <h3>
                Thumbnail label
              </h3>
              <p>
                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
              <p>
                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- / sub-bottom  -->

{% endblock content %}