apps/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
# from api.views import index
from api.views import index, orders

app_name = "api"
urlpatterns = [
    url(r'^$', index.index, name="index"),
    url(r'^order/create/$', orders.create_order, name="create_order"),
]

apps/chief/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from . import views

app_name = "chief"
urlpatterns = [
    url(r'^$', views.ProjectList.as_view(), name='index'),


    url(r'^projects/$', views.ProjectList.as_view(), name='projects'),
    url(r'^project/(?P<pk>[0-9]+)/$', views.ProjectDetails.as_view(), name='project'),
    url(r'^project/create/$', views.ProjectCreate.as_view(), name='project_create'),
    url(r'^project/upd/(?P<pk>[0-9]+)/$', views.ProjectUpdate.as_view(), name='project_upd'),
    url(r'^project/del/(?P<pk>[0-9]+)/$', views.ProjectDelete.as_view(), name='project_del'),


    url(r'^project/(?P<project_pk>[0-9]+)/orders/upd/(?P<order_pk>[0-9]+)/$', views.OrderUpdate.as_view(), name='order_upd'),
    url(r'^orders/del/(?P<pk>[0-9]+)/$', views.OrderDelete.as_view(), name='order_del'),
    url(r'^project/(?P<project_pk>[0-9]+)/orders/create/$', views.OrderCreate.as_view(), name='order_create'),


    url(r'^project/(?P<project_pk>[0-9]+)/orders/fields/$', views.OrderFieldList.as_view(), name='ord_field_list'),
    url(r'^project/(?P<project_pk>[0-9]+)/orders/fields/create/$', views.OrderFieldCreate.as_view(), name='ord_field_create'),
    url(r'^orders/fields/upd/(?P<pk>[0-9]+)/$', views.OrderFieldUpdate.as_view(), name='ord_field_upd'),
    url(r'^orders/fields/del/(?P<pk>[0-9]+)/$', views.OrderFieldDelete.as_view(), name='ord_field_del'),


    url(r'^project/(?P<project_pk>[0-9]+)/invites/$', views.InviteList.as_view(), name='invites'),
    url(r'^invites/del/(?P<pk>[0-9]+)/$', views.InviteDelete.as_view(), name='invite_del'),
    url(r'^invites/create/$', views.InviteCreate.as_view(), name='invite_create'),


    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
]

apps/metaord/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from metaord import settings
from metaord.models import MetaordSettings
from metaord.views import SettingsUpdate


# if settings.DEBUG:
handler404 = 'metaord.views.page_not_found'
handler500 = 'metaord.views.error_view'
handler400 = 'metaord.views.error_view'


urlpatterns = [
    url(r'^', include('front.urls')),
    url(r'^settings/$', SettingsUpdate.as_view(), name='metaord_settings'),
    url(r'^chief/', include('chief.urls')),
    url(r'^webms/', include('webms.urls')),
    url(r'^worker/', include('worker.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/chief/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from webms.models import Webms

class Chief(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bank_account = models.IntegerField()

    def __str__(self):
        return "{0} {1}".format(self.user.first_name, self.user.last_name)

class Project(models.Model):
    name = models.CharField(max_length=512, verbose_name="Название")
    pb_order_create = models.TextField(verbose_name="Тело post-back сообщения при создании заказа в формате JSON", blank=True)
    pb_order_upd_status = models.TextField(verbose_name="Тело post-back сообщения при обновлении статуса заказа в формате JSON", blank=True)
    pb_url = models.URLField(verbose_name="Post-back URL", blank=True)

    def __str__(self):
        return self.name

WEBMS_INV_STATUS_CHOICES_AND_CLASS = [
    (1,       'Новый',                  'label-primary'),
    (2,       'Принят',                 'label-success'),
    (3,       'Отклонён',               'label-warning'),
]
WEBMS_INV_STATUS_CHOICES = list(map(lambda x: x[0:2], WEBMS_INV_STATUS_CHOICES_AND_CLASS))

class WebmsInvite(models.Model):
    api_token = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    webms = models.ForeignKey(Webms, on_delete=models.CASCADE, verbose_name="Web-мастер")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="Проект")
    status = models.IntegerField(choices=WEBMS_INV_STATUS_CHOICES, default=1, verbose_name="Статус приглашения")
    orders_amt = models.IntegerField(default=0, verbose_name="Заказов от приглашения")

    def __str__(self):
        return "Приглашение `{0} {1}` в проект `{2}`".format(self.webms.user.first_name, self.webms.user.last_name, self.project)

apps/metaord/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django import forms
from django.utils import timezone
from django.core.validators import RegexValidator
from worker.models import Operator
from chief.models import Project


class MetaordSettings(models.Model):
    post_back_url = models.CharField(max_length=1024, default="")


# todo: inside of model
STATUS_CHOICES_AND_CLASS = [
    (0,       'Новый',            'label-default'),
    (1,       'Принят',           'label-primary'),
    (2,       'Отменён',          'label-warning'),
    (3,       'Отправлен',        'label-primary'),
    (4,       'Ждёт оплаты',      'label-info'),
    (5,       'Оплачен',          'label-success'),
    (6,       'Перевод',          'label-success'),
    (7,       'Возврат',          'label-danger'),
    (8,       'Дубликат',         'label-default'),
    (9,       'Ошибка',           'label-warning'),
]

STATUS_CHOICES = list(map(lambda x: x[0:2], STATUS_CHOICES_AND_CLASS))

class Order(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    post_date = models.DateTimeField(default=timezone.now)
    status = models.IntegerField(choices=STATUS_CHOICES)
    fields = JSONField(blank=True, null=True) # TODO: try rm

    def __str__(self):
        return 'Order #{0} from project `{1}`. Fields:{2}'.format(self.pk, self.project, self.fields)


FIELD_TYPES_FORMFIELD = [
    (0,         "Строка",       lambda *args, **kwargs: forms.CharField(max_length=256, *args, **kwargs)),
    (1,         "Число",        lambda *args, **kwargs: forms.IntegerField(*args, **kwargs)),
    (2,         "Текст",        lambda *args, **kwargs: forms.CharField(widget=forms.Textarea, *args, **kwargs)),
    (3,         "Флажок",       lambda *args, **kwargs: forms.BooleanField(*args, **kwargs)),
    (4,         "Время",        lambda *args, **kwargs: forms.TimeField(*args, **kwargs)),
    (5,         "Email",        lambda *args, **kwargs: forms.EmailField(*args, **kwargs)),
    (6,         "Телефон",      lambda *args, **kwargs: forms.CharField(validators=[
        RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Некорректный телефон")], *args, **kwargs)),
]

FIELD_TYPES = list(map(lambda x: x[0:2], FIELD_TYPES_FORMFIELD))

class OrderField(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    is_on = models.BooleanField(verbose_name="Включено", default=True)
    name = models.CharField(max_length=256, verbose_name="Имя")
    vtype = models.IntegerField(choices=FIELD_TYPES, verbose_name="Тип")
    is_required = models.BooleanField(verbose_name="Обязательное", default=False)
    pattern = models.CharField(max_length=256, verbose_name="Шаблон", default=".+")
    error_msg = models.CharField(max_length=256, verbose_name="Сообщение об ошибке", default="Одно из полей заполненно неправильно.")
    can_worker_edit = models.BooleanField(verbose_name="Оператор может редактировать", default=True)
    can_webms_view = models.BooleanField(verbose_name="Web-мастер может просматривать", default=True)

    def get_form_field(self):
        fld = FIELD_TYPES_FORMFIELD[self.vtype][2](required=self.is_required, label=self.name)
        fld.validators.append(
            RegexValidator(
                regex=self.pattern,
                message=self.error_msg,
                code='field_{0}_is_invalid'.format(self.name)
            ),
        )
        return fld

    class Meta:
        unique_together = ('project', 'name',)

    def __str__(self):
        return self.name

apps/chief/forms.py
from django.contrib.auth.models import User
from django import forms
from metaord.forms import UserForm
from chief.models import Chief

class ChiefForm(forms.ModelForm):
    class Meta:
        model = Chief
        fields = "__all__" 
        exclude = ['user']

apps/api/views/orders.py
import json
from django.contrib import auth, messages
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from api.models import ApiResponse, ErrCodes, ApiOrder
from chief.models import WebmsInvite, Project
from metaord.models import Order, OrderField, STATUS_CHOICES
from metaord.utils.auth import is_valid_uuid


class Scm():
    """ Order request schema """
    api_token = "api_token"
    order = "order"


def create_order(request):
    try:
        data = json.loads(request.body.decode("utf-8"))
    except ValueError as err:
        return ApiResponse.failure("Value error: `{0}`.".format(err), ErrCodes.format_err)

    if Scm.api_token not in data:
        return ApiResponse.failure("API token not povided.", ErrCodes.arg_err)

    if Scm.order not in data:
        return ApiResponse.failure("Order not povided.", ErrCodes.arg_err)

    tok = data[Scm.api_token]
    if not is_valid_uuid(tok):
        return ApiResponse.failure("API token is incorrect.", ErrCodes.token_err)

    invite = WebmsInvite.objects.filter(api_token=tok).first()
    if not invite:
        return ApiResponse.failure("No invite matching to API token.", ErrCodes.invite_err)

    fields = OrderField.objects.filter(project=invite.project)
    if not fields:
        return ApiResponse.failure("No fields matching to API token.", ErrCodes.fields_not_created_err)

    fields_dicts, form_errors = ApiOrder.validate_order(data[Scm.order], fields)
    if form_errors:
        return ApiResponse.failure_form_not_valid(form_errors)

    o = Order.objects.create(project=invite.project, status=1, fields=fields_dicts)

    return ApiResponse.success()

apps/chief/templates/chief/orders/fields/create.html
{% extends 'metaord/layouts/basic.html' %}
{% load bootstrap3 %}

{% block content %}
<h3>Создание поля заказа</h3>
<form method="POST" action="{% url 'chief:ord_field_create' project_pk=project_pk %}" class="form-horizontal">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}
        <div class="col-sm-offset-3 col-sm-10">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    {% endbuttons %}
</form>
{% endblock %}

apps/chief/templates/chief/orders/fields/delete.html
{% extends 'metaord/layouts/basic.html' %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="mb2">Удаление поля заказа</h3>
    <form method="POST" action="{% url 'chief:ord_field_del' pk=object.pk %}" class="form-horizontal">
        {% csrf_token %}
        <p>Вы действительно хотите удалить поле заказа "<b>{{ object }}</b>"?</p>
        <p>Вся информация хранящаяся в этом поле будет уничтожена.</p>
        {% buttons %}
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary">Удалить</button>
        </div>
        {% endbuttons %}
    </form>
{% endblock content %}

apps/chief/templates/chief/orders/fields/list.html
{% extends 'metaord/layouts/basic.html' %}
{% load bootstrap3 %}
{% load urls_utils %}

{% block content %}
<h3>Список дополнительных полей к заказу</h3>
<div class="mb1"><a href="{% url 'chief:ord_field_create' project_pk=project_pk %}">
    <button type="button" class="btn btn-primary btn-sm">Создать поле</button></a>
</div>
<div class="row col-md-12">
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Проект</th>
            <th>Влючено</th>
            <th>Имя</th>
            <th>Тип</th>
            <th>Обязательное</th>
            <th>Шаблон</th>
            <th>Сообщение об ошибке</th>
            <th>Может ли редактировать оператор</th>
            <th>Может ли просматривать web-мастер</th>
        </tr>
        {% for field in object_list %}
            <tr>
                <td>
                    {% block id %}
                    <span class="p5p">{{ field.pk }}</span>
                    <span class="dropdown">
                        <span class="btn btn-default btn-xs dropdown-toggle" id="dropdownMenu1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <span class="glyphicon glyphicon-option-horizontal"></span>
                        </span>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{% url 'chief:ord_field_upd' pk=field.pk %}">Редактировать</a></li>
                            <li><a href="{% url 'chief:ord_field_del' pk=field.pk %}">Удалить</a></li>
                        </ul>
                    </span>
                    {% endblock id %}
                </td>
                <td>{{ field.project }}</td>
                <td>{{ field.is_on }}</td>
                <td>{{ field.name }}</td>
                <td>{{ field.get_vtype_display }}</td>
                <td>{{ field.is_required }}</td>
                <td>{{ field.pattern }}</td>
                <td>{{ field.error_msg }}</td>
                <td>{{ field.can_worker_edit }}</td>
                <td>{{ field.can_webms_view }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

apps/chief/templates/chief/orders/fields/update.html
{% extends 'metaord/layouts/basic.html' %}
{% load bootstrap3 %}

{% block content %}
<h3>Обновление поля заказа</h3>
<form method="POST" action="{% url 'chief:ord_field_upd' pk=object.pk %}" class="form-horizontal">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}
        <div class="col-sm-offset-3 col-sm-10">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    {% endbuttons %}
</form>
{% endblock %}