apps/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
# from api.views import index
from api.views import index, orders

app_name = "api"
urlpatterns = [
    url(r'^$', index.index, name="index"),
    url(r'^order/create/$', orders.create_order, name="create_order"),
]

apps/chief/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from . import views

app_name = "chief"
urlpatterns = [
    url(r'^$', views.ProjectList.as_view(), name='index'),


    url(r'^projects/$', views.ProjectList.as_view(), name='projects'),
    url(r'^project/(?P<pk>[0-9]+)/$', views.ProjectDetails.as_view(), name='project'),
    url(r'^project/create/$', views.ProjectCreate.as_view(), name='project_create'),
    url(r'^project/upd/(?P<pk>[0-9]+)/$', views.ProjectUpdate.as_view(), name='project_upd'),
    url(r'^project/del/(?P<pk>[0-9]+)/$', views.ProjectDelete.as_view(), name='project_del'),


    url(r'^project/(?P<project_pk>[0-9]+)/orders/upd/(?P<order_pk>[0-9]+)/$', views.OrderUpdate.as_view(), name='order_upd'),
    url(r'^orders/del/(?P<pk>[0-9]+)/$', views.OrderDelete.as_view(), name='order_del'),
    url(r'^project/(?P<project_pk>[0-9]+)/orders/create/$', views.OrderCreate.as_view(), name='order_create'),


    url(r'^project/(?P<project_pk>[0-9]+)/orders/fields/$', views.OrderFieldList.as_view(), name='ord_field_list'),
    url(r'^project/(?P<project_pk>[0-9]+)/orders/fields/create/$', views.OrderFieldCreate.as_view(), name='ord_field_create'),
    url(r'^orders/fields/upd/(?P<pk>[0-9]+)/$', views.OrderFieldUpdate.as_view(), name='ord_field_upd'),
    url(r'^orders/fields/del/(?P<pk>[0-9]+)/$', views.OrderFieldDelete.as_view(), name='ord_field_del'),


    url(r'^project/(?P<project_pk>[0-9]+)/invites/$', views.InviteList.as_view(), name='invites'),
    url(r'^invites/del/(?P<pk>[0-9]+)/$', views.InviteDelete.as_view(), name='invite_del'),
    url(r'^invites/create/$', views.InviteCreate.as_view(), name='invite_create'),


    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
]

apps/metaord/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from metaord import settings
from metaord.models import MetaordSettings
from metaord.views import SettingsUpdate


# if settings.DEBUG:
handler404 = 'metaord.views.page_not_found'
handler500 = 'metaord.views.error_view'
handler400 = 'metaord.views.error_view'


urlpatterns = [
    url(r'^', include('front.urls')),
    url(r'^settings/$', SettingsUpdate.as_view(), name='metaord_settings'),
    url(r'^chief/', include('chief.urls')),
    url(r'^webms/', include('webms.urls')),
    url(r'^worker/', include('worker.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/chief/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from webms.models import Webms

class Chief(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bank_account = models.IntegerField()

    def __str__(self):
        return "{0} {1}".format(self.user.first_name, self.user.last_name)

class Project(models.Model):
    name = models.CharField(max_length=512, verbose_name="Название")
    pb_order_create = models.TextField(verbose_name="Тело post-back сообщения при создании заказа в формате JSON", blank=True)
    pb_order_upd_status = models.TextField(verbose_name="Тело post-back сообщения при обновлении статуса заказа в формате JSON", blank=True)
    pb_url = models.URLField(verbose_name="Post-back URL", blank=True)

    def __str__(self):
        return self.name

WEBMS_INV_STATUS_CHOICES_AND_CLASS = [
    (1,       'Новый',                  'label-primary'),
    (2,       'Принят',                 'label-success'),
    (3,       'Отклонён',               'label-warning'),
]
WEBMS_INV_STATUS_CHOICES = list(map(lambda x: x[0:2], WEBMS_INV_STATUS_CHOICES_AND_CLASS))

class WebmsInvite(models.Model):
    api_token = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    webms = models.ForeignKey(Webms, on_delete=models.CASCADE, verbose_name="Web-мастер")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="Проект")
    status = models.IntegerField(choices=WEBMS_INV_STATUS_CHOICES, default=1, verbose_name="Статус приглашения")
    orders_amt = models.IntegerField(default=0, verbose_name="Заказов от приглашения")

    def __str__(self):
        return "Приглашение `{0} {1}` в проект `{2}`".format(self.webms.user.first_name, self.webms.user.last_name, self.project)

apps/chief/forms.py
from django.contrib.auth.models import User
from django import forms
from metaord.forms import UserForm
from chief.models import Chief

class ChiefForm(forms.ModelForm):
    class Meta:
        model = Chief
        fields = "__all__" 
        exclude = ['user']

apps/chief/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, TemplateView, UpdateView, CreateView, DeleteView
from django.contrib import auth, messages
from django.urls import reverse_lazy
from django import forms
from django.contrib.auth.models import User, Permission
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.http import require_GET, require_POST
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.utils import timezone
from metaord.views import OrderList, OrderCreate as BaseOrderCreate
from metaord.forms import UserForm, build_order_form_class
from metaord.models import OrderField, Order, STATUS_CHOICES_AND_CLASS
from metaord.utils.view import ExtraContext
from metaord.utils.auth import Groups
from metaord.utils.models import create_default_order_fields
from metaord.utils.decorators import group_required, class_decorator
from chief.models import WebmsInvite, Project
from chief.forms import ChiefForm
from functools import partial
# todo: mb distribute by files

login_url = reverse_lazy("login")

@group_required("chief", login_url=login_url)
def index(request):
    return render(request, "chief/index.html", {})


@class_decorator(group_required("chief", login_url=login_url))
class ProjectList(ListView):
    model = Project
    template_name = "chief/projects/projects.html"

@class_decorator(group_required("chief", login_url=login_url))
class ProjectDetails(OrderList):
    template_name = "chief/projects/project.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["project"] = Project.objects.get(pk=self.kwargs["pk"])
        ctx["webms_invites"] = WebmsInvite.objects.filter(project=ctx["project"])
        ctx["extra_fields"] = { field.name : str(field.pk) for field in OrderField.objects.filter(project=ctx["project"]) }
        ctx.update()
        return ctx

    def get_queryset(self):
        qset = super().get_queryset()
        return qset.filter(project=self.kwargs["pk"])

@class_decorator(group_required("chief", login_url=login_url))
class ProjectCreate(SuccessMessageMixin, CreateView):
    model = Project
    template_name = "chief/projects/create.html"
    fields = "__all__"
    success_url = reverse_lazy("chief:projects")
    success_message = "Проект успешно создан"

    def form_valid(self, form):
        proj = form.save()
        create_default_order_fields(proj)
        return HttpResponseRedirect(reverse_lazy("chief:project", kwargs={"pk": proj.pk}))

@class_decorator(group_required("chief", login_url=login_url))
class ProjectUpdate(SuccessMessageMixin, UpdateView):
    model = Project
    template_name = "chief/projects/update.html"
    fields = "__all__"
    success_url = reverse_lazy("chief:projects")
    success_message = "Проект успешно изменён"

@class_decorator(group_required("chief", login_url=login_url))
class ProjectDelete(SuccessMessageMixin, DeleteView):
    model = Project
    template_name = "chief/projects/delete.html"
    fields = "__all__"
    success_url = reverse_lazy("chief:projects")
    success_message = "Проект успешно удалён"


@class_decorator(group_required("chief", login_url=login_url))
class OrderCreate(TemplateView):
    template_name = "chief/orders/create.html"
    success_url = reverse_lazy("chief:projects")
    success_message = "Заказ успешно создан"
    Form = None
    initial = None
    proj_order_fields = []

    def dispatch(self, *args, **kwargs):
        """Construct Form class and set initial if exists"""
        self.proj_order_fields = OrderField.objects.filter(project=self.kwargs["project_pk"])
        self.Form = build_order_form_class(self.proj_order_fields)
        if "order_pk" in self.kwargs:
            order = Order.objects.get(pk=self.kwargs["order_pk"])
            self.initial = {
                "project": order.project.pk,
                "status": order.status,
                "post_date": order.post_date,
            }
            self.initial.update(order.fields)
        return super(OrderCreate, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        form_init = self.initial or {"project": self.kwargs["project_pk"]}
        order_form = self.Form(initial=form_init)
        return render(request, self.template_name, {"form": order_form})

    def post(self, request, *args, **kwargs):
        form = self.Form(request.POST)
        if form.is_valid():
            extra_fields = { str(field.pk) : form.cleaned_data[str(field.pk)] for field in self.proj_order_fields }
            if "order_pk" in self.kwargs:
                o = Order.objects.get(pk=self.kwargs["order_pk"])
                o.project=form.cleaned_data["project"]
                o.status=form.cleaned_data["status"]
                o.fields=extra_fields
                o.save()
            else:
                Order.objects.create(project=form.cleaned_data["project"], status=form.cleaned_data["status"], fields=extra_fields)
            messages.success(request, self.success_message)
            return redirect(reverse_lazy("chief:project", kwargs={"pk": self.kwargs["project_pk"]}), request=request)
        else:
            return render(request, self.template_name, {"form": form})

@class_decorator(group_required("chief", login_url=login_url))
class OrderUpdate(OrderCreate):
    template_name = "chief/orders/update.html"
    success_message = "Заказ успешно обновлён"

@class_decorator(group_required("chief", login_url=login_url))
class OrderDelete(SuccessMessageMixin, DeleteView):
    model = Order
    template_name = "chief/orders/delete.html"
    success_url = reverse_lazy("chief:projects")
    success_message = "Заказ успешно удалён"

    def get_object(self, queryset=None):
        obj = super(OrderDelete, self).get_object(queryset)
        if obj != None:
            self.success_url = reverse_lazy("chief:project", kwargs={"pk": obj.project.pk})
        return obj

@class_decorator(group_required("chief", login_url=login_url))
class OrderFieldList(ListView):
    model = OrderField
    template_name = "chief/orders/fields/list.html"

    def get_context_data(self, **kwargs):
        ctx = super(OrderFieldList, self).get_context_data(**kwargs)
        ctx["project_pk"] = self.kwargs["project_pk"]
        ctx.update()
        return ctx

    def get_queryset(self, **kwargs):
        qset = super(OrderFieldList, self).get_queryset(**kwargs)
        return qset.filter(project=self.kwargs["project_pk"])

@class_decorator(group_required("chief", login_url=login_url))
class OrderFieldCreate(SuccessMessageMixin, CreateView):
    model = OrderField
    fields = "__all__"
    template_name = "chief/orders/fields/create.html"
    success_url = reverse_lazy("chief:projects")
    success_message = "Поле успешно создано"

    def get_initial(self):
        proj = get_object_or_404(Project, pk=self.kwargs["project_pk"])
        return {'project': proj}

    def get_context_data(self, **kwargs):
        ctx = super(OrderFieldCreate, self).get_context_data(**kwargs)
        ctx["project_pk"] = self.kwargs["project_pk"]
        ctx.update()
        return ctx

    def form_valid(self, form):
        self.success_url = reverse_lazy("chief:project", kwargs={"pk": form.instance.project.pk})
        return super(OrderFieldCreate, self).form_valid(form)

@class_decorator(group_required("chief", login_url=login_url))
class OrderFieldUpdate(SuccessMessageMixin, UpdateView):
    model = OrderField
    template_name = "chief/orders/fields/update.html"
    fields = "__all__"
    success_url = reverse_lazy("chief:projects")
    success_message = "Поле успешно изменено"

    def form_valid(self, form):
        self.success_url = reverse_lazy("chief:project", kwargs={"pk": form.instance.project.pk})
        return super(OrderFieldUpdate, self).form_valid(form)

@class_decorator(group_required("chief", login_url=login_url))
class OrderFieldDelete(SuccessMessageMixin, DeleteView):
    model = OrderField
    template_name = "chief/orders/fields/delete.html"
    success_url = reverse_lazy("chief:projects")
    success_message = "Поле успешно удалено"

    def get_object(self, queryset=None):
        obj = super(OrderFieldDelete, self).get_object(queryset)
        if obj != None:
            self.success_url = reverse_lazy("chief:project", kwargs={"pk": obj.project.pk})
        return obj


@class_decorator(group_required("chief", login_url=login_url))
class InviteList(ListView):
    model = WebmsInvite
    template_name = "chief/projects/webms_invites.html"

    def get_queryset(self):
        qset = super().get_queryset()
        return qset.filter(project=self.kwargs["project_pk"])


@class_decorator(group_required("chief", login_url=login_url))
class InviteCreate(SuccessMessageMixin, CreateView):
    model = WebmsInvite
    fields = ["webms", "project"]
    template_name = "chief/webms_invites/create.html"
    success_url = reverse_lazy("chief:projects")
    success_message = "Приглашение успешно создано"

    def form_valid(self, form):
        self.success_url = reverse_lazy("chief:project", kwargs={"pk": form.instance.project.pk})
        return super(InviteCreate, self).form_valid(form)

@class_decorator(group_required("chief", login_url=login_url))
class InviteDelete(SuccessMessageMixin, DeleteView):
    model = WebmsInvite
    template_name = "chief/webms_invites/delete.html"
    success_url = reverse_lazy("chief:projects")
    success_message = "Приглашение успешно удалёно"

    def get_object(self, queryset=None):
        obj = super(InviteDelete, self).get_object(queryset)
        if obj != None:
            self.success_url = reverse_lazy("chief:project", kwargs={"pk": obj.project.pk})
        return obj


class RegistrationView(TemplateView):
    template_name = "chief/register.html"

apps/chief/templates/chief/projects/create.html
{% extends 'metaord/layouts/basic.html' %}
{% load urls_utils %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="mb2">Создание нового проекта</h3>
    <p>Post-back сообщения указываются в формате JSON с возможностью вставки следующих специальных значений:</p>
    {% verbatim %}
    <ul>
        <li>Статус заказа: <code>{{ order.status }}</code></li>
        <li>Дата создания заказа: <code>{{ order.post_date }}</code></li>
        <li>Дополнительные поля заказа: <code>{{ order.fields|lookup:23 }}</code>, где 23 - это ID поля из списка доп полей проекта</li>
    </ul>
    <p>Например:</p>
    <code><pre>
{
    "firstName": {{ order.fields|lookup:23 }},
    "lastName": {{ order.fields|lookup:24 }},
    "address": {
        "streetAddress": {{ order.fields|lookup:25 }}
    },
    "phoneNumbers": [
        {{ order.fields|lookup:26 }}
    ]
}
    </pre></code>
    {% endverbatim %}
    <form method="POST" action="{% url 'chief:project_create' %}" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons %}
            <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-primary">Создать</button>
            </div>
        {% endbuttons %}
    </form>
{% endblock content %}

apps/chief/templates/chief/projects/delete.html
{% extends 'metaord/layouts/basic.html' %}
{% load urls_utils %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="mb2">Удаление проекта</h3>
    <form method="POST" action="{% url 'chief:project_del' pk=project.pk %}" class="form-horizontal">
        {% csrf_token %}
        <p>Вы действительно хотите удалить проект "<b>{{ object }}</b>"?</p>
        <p>Это повлечёт удаление всех заказов данного проекта.</p>
        {% buttons %}
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary">Удалить</button>
        </div>
        {% endbuttons %}
    </form>
{% endblock content %}

apps/chief/templates/chief/projects/project.html
{% extends 'metaord/layouts/basic.html' %}

{% block content %}
    <h2 class="mb2">
        <span><b>{{ project.name }}</b></span>
        <span class="dropdown">
            <span class="btn btn-default btn-sm dropdown-toggle" id="dropdownMenu1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-option-horizontal"></span>
            </span>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="{% url 'chief:project_upd' pk=project.pk %}">Редактировать</a></li>
                <li><a href="{% url 'chief:project_del' pk=project.pk %}">Удалить</a></li>
            </ul>
        </span>
    </h2>

    <div class="mb1">
        <button class="btn btn-default mb1" type="button" data-toggle="collapse" data-target="#invites" aria-expanded="false" aria-controls="invites">
            Приглашения web-мастеров
        </button>
        <div class="collapse" id="invites">
            <div>
                <div class="mb1"><a href="{% url 'chief:invite_create' %}"><button type="button" class="btn btn-primary btn-sm">Новое приглашение</button></a></div>
                {% include "chief/fragments/webms_invites/invites.html" with object_list=webms_invites %}
            </div>
        </div>
    </div>
    <div class="mb2">
        <button class="btn btn-default" type="button" data-toggle="collapse" data-target="#post-back" aria-expanded="false" aria-controls="post-back">
            Post-back
        </button>
        <div class="collapse" id="post-back">
            <div>
                <h4>URL: <code>{{ project.pb_url }}</code></h4>
                <h4>Создание заказа: <pre><code>{{ project.pb_order_create }}</code></pre></h4>
                <h4>Изменение заказа: <pre><code>{{ project.pb_order_upd_status }}</code></pre></h4>
            </div>
        </div>
    </div>

    <h3>
        <span>Заказы</span>
        <span class="dropdown">
            <span class="btn btn-default btn-xs dropdown-toggle" id="dropdownMenu1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-option-horizontal"></span>
            </span>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="{% url 'chief:ord_field_list' project_pk=project.pk %}">Редактировать поля заказа</a></li>
            </ul>
        </span>
    </h3>
    <div class="mb1"><a href="{% url 'chief:order_create' project_pk=project.pk %}">
        <button type="button" class="btn btn-primary btn-sm">Создать заказ</button></a>
    </div>
    <div class="mb2">
    {% include "chief/fragments/orders/orders_list.html" with orders=object_list %}
    </div>
{% endblock content %}

apps/chief/templates/chief/projects/projects.html
{% extends 'metaord/layouts/basic.html' %}

{% block content %}
    <h2>Список проектов</h2>
    <div class="mb1"><a href="{% url 'chief:project_create' %}"><button type="button" class="btn btn-primary btn-sm">Создать проект</button></a></div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Название</th>
        </tr>
        {% for project in object_list %}
            <tr>
                <td>
                    <a class="p5p" href="{% url 'chief:project' pk=project.pk %}">{{ project.pk }}</a>
                    <span class="dropdown">
                        <span class="btn btn-default btn-xs dropdown-toggle" id="dropdownMenu1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <i class="glyphicon glyphicon-option-horizontal"></i>
                        </span>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{% url 'chief:project_upd' pk=project.pk %}">Редактировать</a></li>
                            <li><a href="{% url 'chief:project_del' pk=project.pk %}">Удалить</a></li>
                        </ul>
                    </span>
                </td>
                <td>{{ project.name }}</td>
            </tr>
        {% endfor %}
    </table>
    <h2>Методы API:</h2>
    <h3>Список методов</h3>
    <ul>
        <li><b>/api/order/create</b> - создания заказа. Формат сообщения (FIELD_NAME, VALUE - имя и значение дополнительного поля, API_TOKEN - токен приглашения для web-мастера):
        <pre><code>{
    "api_token": API_TOKEN,
    "order": {
        "FIELD_NAME": VALUE
    }
}</pre></code>
        </li>
    </ul>
{% endblock content %}

apps/chief/templates/chief/projects/update.html
{% extends 'metaord/layouts/basic.html' %}
{% load urls_utils %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="mb2">Изменение проекта</h3>
    <form method="POST" action="{% url 'chief:project_upd' pk=project.pk %}" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}      
        {% buttons %}
            <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        {% endbuttons %}
    </form>
{% endblock content %}

apps/chief/templates/chief/projects/webms_invites.html
{% extends 'metaord/layouts/basic.html' %}

{% block content %}
    <h3>Приглашения web-мастеров</h3>
    <div class="mb1"><a href="{% url 'chief:invite_create' %}"><button type="button" class="btn btn-primary btn-sm">Новое приглашение</button></a></div>
    {% include "chief/fragments/webms_invites/invites.html" with object_list=webms_invites %}
{% endblock content %}